# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parte3.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparte3.proto\x12\tprotoblog\"\xd6\x01\n\x06\x44\x45VICE\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12:\n\x0f\x63onection_state\x18\x02 \x01(\x0e\x32!.protoblog.Device_Conection_State\x1a\x15\n\x04lamp\x12\r\n\x05state\x18\x01 \x01(\t\x1a.\n\x02\x41\x43\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\x12\x13\n\x0bmode_option\x18\x02 \x01(\t\x1a\x34\n\x10IrrigationSystem\x12\r\n\x05state\x18\x01 \x01(\x08\x12\x11\n\tintensity\x18\x02 \x01(\x05\",\n\x07\x44\x45VICES\x12!\n\x06\x64\x65vice\x18\x01 \x03(\x0b\x32\x11.protoblog.DEVICE\"#\n\x07GATEWAY\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"]\n\x07MENSAGE\x12\"\n\x06server\x18\x01 \x01(\x0b\x32\x12.protoblog.GATEWAY\x12!\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32\x11.protoblog.DEVICE\x12\x0b\n\x03msg\x18\x03 \x01(\t*?\n\x16\x44\x65vice_Conection_State\x12\x0f\n\x0b\x44\x45VICE_IDLE\x10\x00\x12\x14\n\x10\x44\x45VICE_CONNECTED\x10\x01\x62\x06proto3')

_DEVICE_CONECTION_STATE = DESCRIPTOR.enum_types_by_name['Device_Conection_State']
Device_Conection_State = enum_type_wrapper.EnumTypeWrapper(_DEVICE_CONECTION_STATE)
DEVICE_IDLE = 0
DEVICE_CONNECTED = 1


_DEVICE = DESCRIPTOR.message_types_by_name['DEVICE']
_DEVICE_LAMP = _DEVICE.nested_types_by_name['lamp']
_DEVICE_AC = _DEVICE.nested_types_by_name['AC']
_DEVICE_IRRIGATIONSYSTEM = _DEVICE.nested_types_by_name['IrrigationSystem']
_DEVICES = DESCRIPTOR.message_types_by_name['DEVICES']
_GATEWAY = DESCRIPTOR.message_types_by_name['GATEWAY']
_MENSAGE = DESCRIPTOR.message_types_by_name['MENSAGE']
DEVICE = _reflection.GeneratedProtocolMessageType('DEVICE', (_message.Message,), {

  'lamp' : _reflection.GeneratedProtocolMessageType('lamp', (_message.Message,), {
    'DESCRIPTOR' : _DEVICE_LAMP,
    '__module__' : 'parte3_pb2'
    # @@protoc_insertion_point(class_scope:protoblog.DEVICE.lamp)
    })
  ,

  'AC' : _reflection.GeneratedProtocolMessageType('AC', (_message.Message,), {
    'DESCRIPTOR' : _DEVICE_AC,
    '__module__' : 'parte3_pb2'
    # @@protoc_insertion_point(class_scope:protoblog.DEVICE.AC)
    })
  ,

  'IrrigationSystem' : _reflection.GeneratedProtocolMessageType('IrrigationSystem', (_message.Message,), {
    'DESCRIPTOR' : _DEVICE_IRRIGATIONSYSTEM,
    '__module__' : 'parte3_pb2'
    # @@protoc_insertion_point(class_scope:protoblog.DEVICE.IrrigationSystem)
    })
  ,
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'parte3_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.DEVICE)
  })
_sym_db.RegisterMessage(DEVICE)
_sym_db.RegisterMessage(DEVICE.lamp)
_sym_db.RegisterMessage(DEVICE.AC)
_sym_db.RegisterMessage(DEVICE.IrrigationSystem)

DEVICES = _reflection.GeneratedProtocolMessageType('DEVICES', (_message.Message,), {
  'DESCRIPTOR' : _DEVICES,
  '__module__' : 'parte3_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.DEVICES)
  })
_sym_db.RegisterMessage(DEVICES)

GATEWAY = _reflection.GeneratedProtocolMessageType('GATEWAY', (_message.Message,), {
  'DESCRIPTOR' : _GATEWAY,
  '__module__' : 'parte3_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.GATEWAY)
  })
_sym_db.RegisterMessage(GATEWAY)

MENSAGE = _reflection.GeneratedProtocolMessageType('MENSAGE', (_message.Message,), {
  'DESCRIPTOR' : _MENSAGE,
  '__module__' : 'parte3_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.MENSAGE)
  })
_sym_db.RegisterMessage(MENSAGE)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICE_CONECTION_STATE._serialized_start=422
  _DEVICE_CONECTION_STATE._serialized_end=485
  _DEVICE._serialized_start=28
  _DEVICE._serialized_end=242
  _DEVICE_LAMP._serialized_start=119
  _DEVICE_LAMP._serialized_end=140
  _DEVICE_AC._serialized_start=142
  _DEVICE_AC._serialized_end=188
  _DEVICE_IRRIGATIONSYSTEM._serialized_start=190
  _DEVICE_IRRIGATIONSYSTEM._serialized_end=242
  _DEVICES._serialized_start=244
  _DEVICES._serialized_end=288
  _GATEWAY._serialized_start=290
  _GATEWAY._serialized_end=325
  _MENSAGE._serialized_start=327
  _MENSAGE._serialized_end=420
# @@protoc_insertion_point(module_scope)
